{% set name = "jupyterlab-js-logs" %}
{% set version = "0.2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0cb4478d33090cdd2aad138e6f8b672a289cc76fd6c6313a63155f60c12ae6af

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - jupyter-packaging >=0.10,<2
  run:
    - jupyterlab >=3.0,<4
    - python >=3.6

test:
  commands:
    - pip check
    - test -f "${PREFIX}/share/jupyter/labextensions/jupyterlab-js-logs/package.json"                                    # [unix]
    - if exist %PREFIX%\\share\\jupyter\\labextensions\\jupyterlab-js-logs\\package.json (exit 0) else (exit 1)          # [win]
  requires:
    - pip

about:
  home: https://github.com/QuantStack/jupyterlab-js-logs
  summary: JupyterLab extension to show the logs from the browser developer tools console
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jtpio
    - hbcarlos
