{% set name = "jupyterlab-js-logs" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: d6419a5b927d17eb031f09a2ab839484d8fc1ee26938cf48bc8727147d9e109a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling >=1.4.0
    - hatch-nodejs-version
    - hatch-jupyter-builder >=0.5
  run:
    - python >={{ python_min }}

test:
  commands:
    - pip check
    - test -f "${PREFIX}/share/jupyter/labextensions/jupyterlab-js-logs/package.json"                                    # [unix]
    - if exist %PREFIX%\\share\\jupyter\\labextensions\\jupyterlab-js-logs\\package.json (exit 0) else (exit 1)          # [win]
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jupyterlab-contrib/jupyterlab-js-logs
  summary: JupyterLab extension to show the logs from the browser developer tools console
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - krassowski
    - jtpio
    - hbcarlos
